#alias tmux='tmux -2'
alias less='less -R'
alias diff='colordiff'
alias glog='git log --oneline --graph --color --all --decorate'
alias ping='ping -O'
alias update='apt update && apt upgrade'
alias supdate='sudo apt update && sudo apt upgrade'
alias ls='ls -lah --color=auto'
alias kgnome='killall -3 gnome-shell'
alias mvallsub='mv */* . ; mv */* . ; mv */* . ; mv */* . ; mv */* . ; mv */* . ; mv */* . ; mv */* . ; cd ..'
alias dcr='docker-compose down;docker-compose up -d'
